### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Lemonsflo** [JoaoPBarros/youtube-loader#1]
Explain to the beginner how and where to install it?

**Comment by JoaoPBarros** [comment]
Hi, first things first, do you know how to use terminal, git and an ide ? If you do not, see this tutorial https://github.com/JoaoPBarros/projects-and-applications/tree/master/facebook-signup/firstStep is in portuguese but is simple to understand.

If you already know git and the basics, open the terminal in the directory you want to put the application. Type the following command: 
    > git clone https://github.com/JoaoPBarros/youtube-loader.git
    > cd youtube-loader

This firsts two comands will clone the repository and open the directory with the application.

After you clone and open the application, enter in https://console.cloud.google.com/home create a new project, click in credentials and you will see this screen: 
![image](https://user-images.githubusercontent.com/65774209/143585332-1e6c26df-e264-4eb4-97d7-4245d11c89fd.png)

In your screen will not have the registered API keys or registered OAuth 2.0 Client IDs, to resolve this you will need to create your on API key and OAuth 2.0 Client ID, one of each is enough. 

When you already have the key and you will change in App.jsx the value of a constant API_KEY to " your_on_api_key"
and when you already have the id you will change in google_sso.jsx which is inside the directory components, change the value of a constant clientIdGoogle to " your_on_id_client"

**NOTE:** The correct is to put those variables as environment variables, but this repository is to transmit knowlodge.

After you follow this you will able to run correctly the application, and you can run the following commands:

> yarn install 
> yarn dev

and after this commands enter in your browser and open http://localhost:8080 and you will see the button login with google and after authorized by google will redirect to a search page. 

I hope the explanation was helpful. If you have any questions, please ask
